# 基于 ppyoloe_plus_crn_m_80e_coco.yml
_BASE_: [
  '../runtime.yml',
  './_base_/optimizer_80e.yml',
  './_base_/ppyoloe_plus_crn.yml',
  './_base_/ppyoloe_plus_reader.yml',
]

metric: VOC
map_type: 11point
num_classes: 3

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/Helmet
    anno_path: train_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/Helmet
    anno_path: val_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/Helmet/labels.txt

log_iter: 100
snapshot_epoch: 5
weights: models/ppyoloe_plus_crn_m_80e_coco.pdparams

pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_m_obj365_pretrained.pdparams
depth_mult: 0.67
width_mult: 0.75
